// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shocker_Project.Models
{
    public partial class Addresses
    {
        public Addresses()
        {
            Orders = new HashSet<Orders>();
        }

        public string Address { get; set; }
        public string UserAccount { get; set; }

        public virtual Users UserAccountNavigation { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}