// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shocker_Project.Models
{
    public partial class Coupons
    {
        public Coupons()
        {
            OrderDetails = new HashSet<OrderDetails>();
        }

        public string CouponId { get; set; }
        public DateTimeOffset ExpirationDate { get; set; }
        public string HolderAccount { get; set; }
        public int ProductCategoryId { get; set; }
        public string Discount { get; set; }
        public string Status { get; set; }
        public string PublisherAccount { get; set; }

        public virtual Users HolderAccountNavigation { get; set; }
        public virtual ProductCategories ProductCategory { get; set; }
        public virtual Users PublisherAccountNavigation { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}