// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Shocker_Project.Models
{
    public partial class Orders
    {
        public Orders()
        {
            OrderDetails = new HashSet<OrderDetails>();
            Ratings = new HashSet<Ratings>();
        }

        public int OrderId { get; set; }
        public string BuyerAccount { get; set; }
        
        public string Address { get; set; }
        public DateTimeOffset OrderDate { get; set; }
        public DateTimeOffset RequiredDate { get; set; }
        [DisplayName("電話")]
        [RegularExpression("@{0-9}[10]",ErrorMessage="電話號碼必須10個數字")]
        public int BuyerPhone { get; set; }
        public string PayMethod { get; set; }
        public string Status { get; set; }

        public virtual Addresses Addresses { get; set; }
        public virtual Users BuyerAccountNavigation { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<Ratings> Ratings { get; set; }
    }
}