// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shocker_Project.Models
{
    public partial class OrderDetails
    {
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int? CouponId { get; set; }
        public int Quantity { get; set; }
        public string Status { get; set; }
        public string ReturnReason { get; set; }
        public string ProductName { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal? Discount { get; set; }
        public string Currency { get; set; }

        public virtual Coupons Coupon { get; set; }
        public virtual Orders Order { get; set; }
        public virtual Products Product { get; set; }
        public virtual Status StatusNavigation { get; set; }
    }
}