// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shocker_Project.Models
{
    public partial class Ratings
    {
        public int ProductId { get; set; }
        public string Description { get; set; }
        public int StarCount { get; set; }
        public int OrderId { get; set; }
        public string Reply { get; set; }
        public string Status { get; set; }

        public virtual Orders Order { get; set; }
        public virtual Products Product { get; set; }
    }
}