// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shocker_Project.Models
{
    public partial class Status
    {
        public Status()
        {
            ClientCases = new HashSet<ClientCases>();
            Coupons = new HashSet<Coupons>();
            OrderDetails = new HashSet<OrderDetails>();
            Orders = new HashSet<Orders>();
            Products = new HashSet<Products>();
            Ratings = new HashSet<Ratings>();
        }

        public string StatusId { get; set; }
        public string StatusName { get; set; }

        public virtual ICollection<ClientCases> ClientCases { get; set; }
        public virtual ICollection<Coupons> Coupons { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<Ratings> Ratings { get; set; }
    }
}