// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Shocker_Project.Areas.Customerservice.Models
{
    public partial class db_a98a02_thm101team1001Context : DbContext
    {
        public db_a98a02_thm101team1001Context()
        {
        }

        public db_a98a02_thm101team1001Context(DbContextOptions<db_a98a02_thm101team1001Context> options)
            : base(options)
        {
        }

        public virtual DbSet<QuestionCategories> QuestionCategories { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<QuestionCategories>(entity =>
            {
                entity.HasKey(e => e.CategoryId);

                entity.Property(e => e.CategoryId).HasColumnName("CategoryID");

                entity.Property(e => e.CategoryName)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}