// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shocker_Project.Areas.Customerservice.Models
{
    public partial class QuestionCategories
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
    }
}