// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shocker_Project.Areas.Models
{
    public partial class ProductCategories
    {
        public ProductCategories()
        {
            Coupons = new HashSet<Coupons>();
            Products = new HashSet<Products>();
        }

        public int CategoryId { get; set; }
        public string CategoryName { get; set; }

        public virtual ICollection<Coupons> Coupons { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}